name: railroad_crossing
description: railroad crossing simulator
publish_to: 'none'
version: 1.3.4+39

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter_android: ^4.7.0
  webview_flutter: ^4.13.0
  # Firebase Analytics
  firebase_core: ^3.15.1
  firebase_analytics: ^11.5.2
  firebase_app_check: ^0.3.2+9
  # App Icon
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  # Audio Player
  # audioplayers: ^6.5.0
  just_audio: ^0.10.4
  path: ^1.9.1
  # Vibration
  vibration: ^3.1.3
  # SharedPreference
  shared_preferences: ^2.5.3
  # Floating Button
  fab_circular_menu_plus: ^0.0.3
  # Admob
  google_mobile_ads: ^6.0.0
  app_tracking_transparency: ^2.0.6+1
  # Device locale
  devicelocale: ^0.8.1
  # OS version
  device_info_plus: ^11.5.0
  #env
  flutter_dotenv: ^5.2.1
  # Revenue Cat
  purchases_flutter: ^8.10.5
  # HyperLink
  url_launcher: ^6.3.1
  #MVVM
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2
  #Generative AI
  firebase_ai: ^2.2.1
  googleapis_auth: ^2.0.0
  http: ^1.4.0
  #Server Time
  ntp: ^2.0.0
  #Save Image
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  image_gallery_saver: ^2.0.3
  share_plus: ^11.0.0

  # Localize
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # App Splash
  flutter_native_splash: ^2.4.6

flutter_icons:
  image_path: "assets/icon/appIcon.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter_native_splash:
  image: "assets/icon/icon.png"
  color: "#ffffff"
  android_12:
    image: "assets/icon/icon.png"
    icon_background_color: "#ffffff"
  ios: true
  web: false

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/images/
    - assets/images/flag/
    - assets/images/crossing/
    - assets/images/crossing/jp/
    - assets/images/crossing/uk/
    - assets/images/crossing/cn/
    - assets/images/crossing/us/
    - assets/images/photo/uk/
    - assets/images/photo/jp/
    - assets/images/photo/cn/
    - assets/images/photo/us/
    - assets/images/train/jp/
    - assets/images/train/uk/
    - assets/images/train/cn/
    - assets/images/train/us/
    - assets/audios/
    - assets/audios/jp/
    - assets/audios/uk/
    - assets/audios/cn/
    - assets/audios/us/
    - assets/fonts/
    - assets/

  fonts:
    - family: beon
      fonts:
        - asset: assets/fonts/beon.ttf
